<a href="https://colab.research.google.com/github/suhasbhairav/scikit/blob/main/ScikitLearnPractise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x0, x1 = np.random.randn(10, 2), np.random.randn(10, 2) + (1, 1)
x = np.vstack((x0, x1))
y = [0] * 10 + [1] * 10

In [3]:
from sklearn import svm

In [8]:
svm.SVC(kernel='linear').fit(x,y).predict([[0,0]])

array([0])

In [9]:
svm.SVR(kernel='linear').fit(x,y).predict([[0,0]])

array([0.2710199])

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [11]:
train = [[1,2,3],[2,5,1],[2,1,7]]
target = [0,1,0]

In [12]:
rf = RandomForestClassifier(n_estimators=100)

In [14]:
rf.fit(train, target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [17]:
test = [[2,2,3]]

In [18]:
rf.predict(test)

array([0])

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
train = [[1,2,3],[2,5,1],[2,1,7]]
target = [0,1,0]

In [21]:
rf = RandomForestClassifier(n_estimators=100)

In [22]:
rf.fit(train, target)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [23]:
rf.predict([[2,2,3]])

array([0])

In [24]:
from sklearn.metrics import classification_report

In [25]:
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
target_names = ['class 0', 'class 1', 'class 2']

In [26]:
print(classification_report(y_true=y_true, y_pred=y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.50      1.00      0.67         1
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.67      0.80         3

    accuracy                           0.60         5
   macro avg       0.50      0.56      0.49         5
weighted avg       0.70      0.60      0.61         5



In [27]:
from sklearn.datasets import load_iris

In [28]:
iris_dataset = load_iris()

In [29]:
X, y = iris_dataset['data'], iris_dataset['target']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8)

In [33]:
from sklearn.ensemble import GradientBoostingClassifier

In [34]:
clf = GradientBoostingClassifier()

In [35]:
clf.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [36]:
clf.predict_proba(X_test)

array([[1.25700286e-04, 9.99777509e-01, 9.67909067e-05],
       [1.15367609e-04, 7.50121214e-05, 9.99809620e-01],
       [1.25728543e-04, 9.99777481e-01, 9.67909040e-05],
       [2.07972076e-04, 2.01260030e-04, 9.99590768e-01],
       [1.25728543e-04, 9.99777481e-01, 9.67909040e-05],
       [9.99758767e-01, 1.04608828e-04, 1.36624179e-04],
       [6.31574826e-03, 6.11768191e-03, 9.87566570e-01],
       [9.99758767e-01, 1.04608828e-04, 1.36624179e-04],
       [1.15367609e-04, 7.50121214e-05, 9.99809620e-01],
       [1.14101725e-04, 7.50122164e-05, 9.99810886e-01],
       [1.15367609e-04, 7.50121214e-05, 9.99809620e-01],
       [9.74796958e-04, 9.96692132e-01, 2.33307119e-03],
       [1.25778626e-04, 9.99777430e-01, 9.67908991e-05],
       [1.15367609e-04, 7.50121214e-05, 9.99809620e-01],
       [2.07925339e-04, 2.01260039e-04, 9.99590815e-01],
       [9.99758767e-01, 1.04608828e-04, 1.36624179e-04],
       [9.99758767e-01, 1.04608828e-04, 1.36624179e-04],
       [1.25728543e-04, 9.99777

In [38]:
clf.score(X_test, y_test)

0.9

In [39]:
from sklearn.ensemble import RandomForestClassifier

In [40]:
clf = RandomForestClassifier(n_estimators=100)

In [41]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [42]:
clf.score(X_test, y_test)

0.9

In [43]:
from sklearn.ensemble import ExtraTreesClassifier

In [44]:
clf = ExtraTreesClassifier()

In [45]:
clf.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [46]:
clf.score(X_test, y_test)

0.9

In [47]:
from sklearn.tree import DecisionTreeClassifier

In [48]:
clf = DecisionTreeClassifier()

In [49]:
clf.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [50]:
clf.score(X_test, y_test)

0.9

In [51]:
import numpy as np

In [52]:
np.random.seed(123) # we'll set a random seed so that our results are reproducible
X = np.hstack((np.random.randn(100, 2) + (10, 10), 0.001 * np.random.randn(100, 5)))

In [53]:
from sklearn.decomposition import PCA

In [54]:
pca = PCA(n_components=2)

In [55]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [56]:
pca.components_

array([[-2.84271217e-01, -9.58743893e-01, -8.25412629e-05,
         1.96237855e-05, -1.25862328e-05,  8.27127496e-05,
        -9.46906600e-05],
       [-9.58743890e-01,  2.84271223e-01, -7.33055823e-05,
        -1.23188872e-04, -1.82458739e-05,  5.50383246e-05,
         1.96503690e-05]])

In [57]:
pca.explained_variance_

array([1.25758064, 0.94718566])

In [58]:
pca.explained_variance_ratio_

array([0.57039059, 0.42960728])

In [59]:
import numpy as np

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
from sklearn.datasets import load_iris

In [62]:
from sklearn import svm

In [63]:
iris_dataset = load_iris()

In [64]:
X, y = iris_dataset['data'], iris_dataset['target']

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8, test_size=0.2)

In [66]:
clf = svm.SVC(kernel='linear', C=1).fit(X_train, y_train)

In [67]:
clf.score(X_test, y_test)

0.9666666666666667

In [68]:
from sklearn.model_selection import KFold

In [69]:
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([1, 2, 1, 2])

In [70]:
cv = KFold(n_splits=3, random_state=0)

/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
